### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by Kcko** [andreCatita/teamRating#1]
Hi @andreCatita ,

I know it's been a long time since you did that. 
But I'm gonna give it a shot.

For the 1 player vs 1 player game, I use the classic ELO RATING.

For a team game (multiple players vs multiple players) I wanted to try yours.

But e.g. if playing only 2 player teams (ie 2 vs 2) with a total rating of 2000 vs 1700

```
$teamA = array(
    array("elo" => 1000),
    array("elo" => 1000),
);

$teamB = array(
    array("elo" => 900),
    array("elo" => 800),
);
```
 

(So for classic there would be roughly 5 points in the game.

But here it's 0, it seems to me that it somehow works if there are a lot of players in teams at least (4vs4 or more) and they have very different scores.

Is there any way to adjust this?

Thanks for the answer :-)

Screen

![](https://bit.ly/3WoiuME)

**Comment by andreCatita** [comment]
Hello @Kcko ,

Two things, one you would be wise to set up the $media_scale_rank, as the default starting elo for your players.

Second, apparently I've hardcoded a 5 player in the math, as I was thinking of normal game of MOBAs.
When calculating the $rating_over_average (there's two times), be sure to divide not by 5, but by the length of the team's size.
